import type { Charity } from './types'

export const INSPIRED_CHARITIES: Charity[] = [
  {
    name: 'charity: water',
    cause: 'Provide Clean Water',
    description: 'Bringing clean and safe drinking water to everyone on the planet',
    logo: 'https://www.charitywater.org/assets/images/global/charity-water-logo-dark.svg',
    url: 'https://www.inspired.com/charity-water',
  },
  {
    name: 'American Diabetes Association',
    cause: 'Cure Diabetes',
    description: 'Prevent and cure diabetes and improve the lives of all people affected',
    logo: 'https://diabetes.org/themes/custom/ada/logo.svg',
    url: 'https://www.inspired.com/american-diabetes-association',
  },
  {
    name: 'Trees for the Future',
    cause: 'Plant Trees',
    description: 'Reforesting the world to combat climate change and nurture a sustainable future',
    logo: 'https://trees.org/wp-content/uploads/2020/01/TREES-logo-horizontal-color.png',
    url: 'https://www.inspired.com/trees',
  },
  {
    name: 'Team Rubicon',
    cause: 'Deliver Disaster Relief',
    description: 'Serving global communities before, during, and after disasters and crises',
    logo: 'https://teamrubiconusa.org/wp-content/uploads/2021/01/TR-Logo-Horizontal-Red-1.png',
    url: 'https://www.inspired.com/team-rubicon',
  },
  {
    name: 'Baby2Baby',
    cause: 'Support Children & Families',
    description: 'Providing children in need with diapers, clothing and all basic necessities',
    logo: 'https://baby2baby.org/wp-content/uploads/2021/06/Baby2Baby-Logo.png',
    url: 'https://www.inspired.com/baby2baby',
  },
  {
    name: 'Partnership for a Healthier America',
    cause: 'Advance Food Equity',
    description: 'Ensuring a healthier America powered by good food for all',
    logo: 'https://ahealthieramerica.org/wp-content/uploads/2019/09/PHA-logo.png',
    url: 'https://www.inspired.com/partnership-for-a-healthier-america',
  },
  {
    name: 'To Write Love On Her Arms',
    cause: 'Prioritize Mental Health',
    description: 'Supporting people struggling with depression, addiction, self-injury, and suicide',
    logo: 'https://twloha.com/wp-content/themes/twloha/img/twloha-logo.svg',
    url: 'https://www.inspired.com/to-write-love-on-her-arms',
  },
  {
    name: 'Malala Fund',
    cause: 'Girls Education',
    description: 'Working for a world where every girl can learn and choose her own future',
    logo: 'https://malala.org/assets/images/malala-fund-logo.svg',
    url: 'https://www.inspired.com/malala-fund',
  },
  {
    name: 'International Justice Mission',
    cause: 'Fight Human Trafficking',
    description: 'Protecting people in poverty from violence and bringing criminals to justice',
    logo: 'https://www.ijm.org/wp-content/themes/ijm/dist/images/ijm-logo.svg',
    url: 'https://www.inspired.com/international-justice-mission',
  },
  {
    name: 'NextStep',
    cause: 'Support Recovery & Fitness',
    description: 'Making life-changing rehab accessible and affordable to those living with paralysis',
    logo: 'https://nextstepfitness.org/wp-content/uploads/2020/01/NextStep-Logo.png',
    url: 'https://nextstepfitness.org',
  },
  {
    name: 'Playing For Change',
    cause: 'Drive Change Through Music',
    description: 'Using music and culture to bring communities together and solve global challenges',
    logo: 'https://playingforchange.com/wp-content/uploads/2020/01/pfc-logo.png',
    url: 'https://www.inspired.com/playing-for-change',
  },
  {
    name: 'Coral Reef Alliance',
    cause: 'Protect Coral Reefs',
    description: 'Keeping coral reefs healthy so they can adapt to climate change and survive',
    logo: 'https://coral.org/wp-content/uploads/2020/07/CORAL-logo.png',
    url: 'https://www.inspired.com/coral-reef-alliance',
  },
  {
    name: 'PeacePlayers International',
    cause: 'Promote Change Through Sports',
    description: 'Unite, educate, and inspire young people in divided communities through basketball',
    logo: 'https://peaceplayers.org/wp-content/uploads/2019/10/PeacePlayers-Logo.png',
    url: 'https://www.inspired.com/peaceplayers',
  },
  {
    name: 'National Urban League',
    cause: 'Promote Equity & Justice',
    description: 'Enabling African Americans and underserved urban residents to secure economic self-reliance',
    logo: 'https://nul.org/sites/default/files/2020-01/NUL-logo.png',
    url: 'https://www.inspired.com/national-urban-league',
  },
  {
    name: 'Equality Now',
    cause: 'Promote Gender Equality',
    description: 'Achieve legal and systemic change addressing violence and discrimination against women and girls',
    logo: 'https://equalitynow.org/wp-content/uploads/2021/01/equality-now-logo.svg',
    url: 'https://www.inspired.com/equality-now',
  },
  {
    name: 'Crisis Text Line',
    cause: 'Support Mental Health',
    description: 'Promote mental well-being for people wherever they are',
    logo: 'https://www.crisistextline.org/wp-content/uploads/2020/06/CTL-logo.svg',
    url: 'https://www.inspired.com/crisis-text-line',
  },
  {
    name: 'USA for UNHCR',
    cause: 'Support Immigrants & Refugees',
    description: 'Protect and support refugees by raising awareness and advocating for their rights',
    logo: 'https://www.unrefugees.org/wp-content/uploads/2019/03/UNHCR-USA-logo.png',
    url: 'https://www.inspired.com/usa-for-unhcr',
  },
  {
    name: 'Action Against Hunger',
    cause: 'Fight Global Hunger',
    description: 'Ending hunger, for everyone, for good',
    logo: 'https://www.actionagainsthunger.org/wp-content/uploads/2020/06/AAH-logo.svg',
    url: 'https://www.inspired.com/action-against-hunger',
  },
  {
    name: 'Big Brothers Big Sisters of America',
    cause: "Build Youth's Future",
    description: 'Create and support one-to-one mentoring relationships that ignite the power and promise of youth',
    logo: 'https://www.bbbs.org/wp-content/uploads/BBBSA-logo.svg',
    url: 'https://www.inspired.com/big-brothers-big-sisters-of-america',
  },
  {
    name: 'Amnesty International USA',
    cause: 'Protect Human Rights',
    description: "Protect people's rights to freedom, justice, and dignity",
    logo: 'https://www.amnestyusa.org/wp-content/uploads/2017/04/aiusa_logo.svg',
    url: 'https://www.inspired.com/amnesty-international-usa',
  },
]
